name    'vicinus-hiera'
version '0.2.0'
source 'git://github.com/vicinus/vicinus-hiera.git'
author 'Reinhard Vicinus'
license 'Apache License, Version 2.0'
summary 'Alternative hiera connector'
description 'Alternative hiera connector'
project_page 'http://github.com/vicinus/vicinus-hiera'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
